"""
Pydantic schemas for the AI Career Guide, conversational counselor, and skill extractor.
"""
from typing import List, Optional
from uuid import UUID
from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Chat
# ---------------------------------------------------------------------------
class ChatRequest(BaseModel):
    student_id: UUID = Field(..., description="ID of the student initiating the chat")
    message: str = Field(..., min_length=1, max_length=2000, description="Student query or message")
    language: Optional[str] = Field("en", description="Preferred language code (e.g. en, hi, mr, bn)")
    session_id: Optional[UUID] = Field(None, description="Existing session ID for multi-turn context")


class OpportunityReference(BaseModel):
    id: UUID
    title: str
    type: str
    official_url: Optional[str] = None
    deadline: Optional[str] = None
    match_reason: Optional[str] = None


class ChatResponse(BaseModel):
    reply: str
    suggested_actions: List[str] = Field(default_factory=list)
    referenced_opportunities: List[OpportunityReference] = Field(default_factory=list)
    is_fallback: bool = Field(False, description="True if generated by local deterministic fallback engine")
    session_id: Optional[UUID] = Field(None, description="Session ID for continuing this conversation")


# ---------------------------------------------------------------------------
# Skill Extraction
# ---------------------------------------------------------------------------
class SkillExtractionRequest(BaseModel):
    description: str = Field(..., min_length=3, max_length=2000, description="Informal learning or hands-on experience text")


class SkillExtractionResponse(BaseModel):
    extracted_skills: List[str] = Field(default_factory=list)
    recommended_trades: List[str] = Field(default_factory=list)
    summary: str


# ---------------------------------------------------------------------------
# Chat Sessions
# ---------------------------------------------------------------------------
class ChatSessionCreate(BaseModel):
    student_id: UUID = Field(..., description="Student who owns this session")
    title: Optional[str] = Field(None, max_length=500, description="Optional session title")


class ChatMessageResponse(BaseModel):
    id: UUID
    role: str
    content: str
    created_at: datetime
    metadata: Optional[dict] = None

    model_config = ConfigDict(from_attributes=True)


class ChatSessionResponse(BaseModel):
    id: UUID
    student_id: UUID
    title: Optional[str]
    created_at: datetime
    last_active_at: datetime
    messages: List[ChatMessageResponse] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class ChatSessionListItem(BaseModel):
    id: UUID
    title: Optional[str]
    created_at: datetime
    last_active_at: datetime
    message_count: Optional[int] = None

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Embedding Management
# ---------------------------------------------------------------------------
class EmbedDocumentResponse(BaseModel):
    document_id: UUID
    chunks_created: int
    message: str


class EmbedAllResponse(BaseModel):
    documents_processed: int
    total_chunks_created: int
    errors: List[str] = Field(default_factory=list)
